apiVersion: skaffold/v3
kind: Config
metadata:
  name: talking-bots
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: registry.digitalocean.com/rewohub/talking-bots-chad-gpt
    context: chad-gpt
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .
        - src: "src/*.ts"
          dest: .
  - image: registry.digitalocean.com/rewohub/talking-bots-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.html"
          dest: .
        - src: "src/**/*.ts"
          dest: .
        - src: "src/**/*.json"
          dest: .
        - src: "src/*.ts"
          dest: .
        - src: "src/**/*.vue"
          dest: .
manifests:
  rawYaml:
  - infra/k8s-dev/bots/**
  - infra/k8s-dev/ingress.yaml
deploy:
  kubeContext: docker-desktop
portForward:
  - resourceType: service
    resourceName: talking-bots-bot-1-service
    port: 3000
    localPort: 4001
  - resourceType: service
    resourceName: talking-bots-bot-2-service
    port: 3000
    localPort: 4002
